env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - eslint:recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
  - '@typescript-eslint'
  - sort-imports-es6-autofix
  - mui-path-imports
rules:
  no-unused-vars: 'off'
  no-console: 'warn'
  prefer-template: 'warn'
  no-undef: 'off'
  'react-hooks/exhaustive-deps': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  '@typescript-eslint/no-unnecessary-condition': 'warn'
  '@typescript-eslint/no-unnecessary-type-assertion': 'warn'
  'mui-path-imports/mui-path-imports': 'error'
ignorePatterns:
  - 'node_modules'
  - 'ts/models.ts'
