// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"capstone-cs.eng.utah.edu/mapeleven/mapeleven/ent/league"
	"capstone-cs.eng.utah.edu/mapeleven/mapeleven/ent/predicate"
	"capstone-cs.eng.utah.edu/mapeleven/mapeleven/ent/season"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SeasonUpdate is the builder for updating Season entities.
type SeasonUpdate struct {
	config
	hooks    []Hook
	mutation *SeasonMutation
}

// Where appends a list predicates to the SeasonUpdate builder.
func (su *SeasonUpdate) Where(ps ...predicate.Season) *SeasonUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetYear sets the "year" field.
func (su *SeasonUpdate) SetYear(i int) *SeasonUpdate {
	su.mutation.ResetYear()
	su.mutation.SetYear(i)
	return su
}

// AddYear adds i to the "year" field.
func (su *SeasonUpdate) AddYear(i int) *SeasonUpdate {
	su.mutation.AddYear(i)
	return su
}

// SetStart sets the "start" field.
func (su *SeasonUpdate) SetStart(t time.Time) *SeasonUpdate {
	su.mutation.SetStart(t)
	return su
}

// SetEnd sets the "end" field.
func (su *SeasonUpdate) SetEnd(t time.Time) *SeasonUpdate {
	su.mutation.SetEnd(t)
	return su
}

// SetCurrent sets the "current" field.
func (su *SeasonUpdate) SetCurrent(b bool) *SeasonUpdate {
	su.mutation.SetCurrent(b)
	return su
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (su *SeasonUpdate) SetNillableCurrent(b *bool) *SeasonUpdate {
	if b != nil {
		su.SetCurrent(*b)
	}
	return su
}

// SetLeagueID sets the "league" edge to the League entity by ID.
func (su *SeasonUpdate) SetLeagueID(id int) *SeasonUpdate {
	su.mutation.SetLeagueID(id)
	return su
}

// SetNillableLeagueID sets the "league" edge to the League entity by ID if the given value is not nil.
func (su *SeasonUpdate) SetNillableLeagueID(id *int) *SeasonUpdate {
	if id != nil {
		su = su.SetLeagueID(*id)
	}
	return su
}

// SetLeague sets the "league" edge to the League entity.
func (su *SeasonUpdate) SetLeague(l *League) *SeasonUpdate {
	return su.SetLeagueID(l.ID)
}

// Mutation returns the SeasonMutation object of the builder.
func (su *SeasonUpdate) Mutation() *SeasonMutation {
	return su.mutation
}

// ClearLeague clears the "league" edge to the League entity.
func (su *SeasonUpdate) ClearLeague() *SeasonUpdate {
	su.mutation.ClearLeague()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SeasonUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, SeasonMutation](ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SeasonUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SeasonUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SeasonUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SeasonUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(season.Table, season.Columns, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Year(); ok {
		_spec.SetField(season.FieldYear, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedYear(); ok {
		_spec.AddField(season.FieldYear, field.TypeInt, value)
	}
	if value, ok := su.mutation.Start(); ok {
		_spec.SetField(season.FieldStart, field.TypeTime, value)
	}
	if value, ok := su.mutation.End(); ok {
		_spec.SetField(season.FieldEnd, field.TypeTime, value)
	}
	if value, ok := su.mutation.Current(); ok {
		_spec.SetField(season.FieldCurrent, field.TypeBool, value)
	}
	if su.mutation.LeagueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.LeagueTable,
			Columns: []string{season.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.LeagueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.LeagueTable,
			Columns: []string{season.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{season.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SeasonUpdateOne is the builder for updating a single Season entity.
type SeasonUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SeasonMutation
}

// SetYear sets the "year" field.
func (suo *SeasonUpdateOne) SetYear(i int) *SeasonUpdateOne {
	suo.mutation.ResetYear()
	suo.mutation.SetYear(i)
	return suo
}

// AddYear adds i to the "year" field.
func (suo *SeasonUpdateOne) AddYear(i int) *SeasonUpdateOne {
	suo.mutation.AddYear(i)
	return suo
}

// SetStart sets the "start" field.
func (suo *SeasonUpdateOne) SetStart(t time.Time) *SeasonUpdateOne {
	suo.mutation.SetStart(t)
	return suo
}

// SetEnd sets the "end" field.
func (suo *SeasonUpdateOne) SetEnd(t time.Time) *SeasonUpdateOne {
	suo.mutation.SetEnd(t)
	return suo
}

// SetCurrent sets the "current" field.
func (suo *SeasonUpdateOne) SetCurrent(b bool) *SeasonUpdateOne {
	suo.mutation.SetCurrent(b)
	return suo
}

// SetNillableCurrent sets the "current" field if the given value is not nil.
func (suo *SeasonUpdateOne) SetNillableCurrent(b *bool) *SeasonUpdateOne {
	if b != nil {
		suo.SetCurrent(*b)
	}
	return suo
}

// SetLeagueID sets the "league" edge to the League entity by ID.
func (suo *SeasonUpdateOne) SetLeagueID(id int) *SeasonUpdateOne {
	suo.mutation.SetLeagueID(id)
	return suo
}

// SetNillableLeagueID sets the "league" edge to the League entity by ID if the given value is not nil.
func (suo *SeasonUpdateOne) SetNillableLeagueID(id *int) *SeasonUpdateOne {
	if id != nil {
		suo = suo.SetLeagueID(*id)
	}
	return suo
}

// SetLeague sets the "league" edge to the League entity.
func (suo *SeasonUpdateOne) SetLeague(l *League) *SeasonUpdateOne {
	return suo.SetLeagueID(l.ID)
}

// Mutation returns the SeasonMutation object of the builder.
func (suo *SeasonUpdateOne) Mutation() *SeasonMutation {
	return suo.mutation
}

// ClearLeague clears the "league" edge to the League entity.
func (suo *SeasonUpdateOne) ClearLeague() *SeasonUpdateOne {
	suo.mutation.ClearLeague()
	return suo
}

// Where appends a list predicates to the SeasonUpdate builder.
func (suo *SeasonUpdateOne) Where(ps ...predicate.Season) *SeasonUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SeasonUpdateOne) Select(field string, fields ...string) *SeasonUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Season entity.
func (suo *SeasonUpdateOne) Save(ctx context.Context) (*Season, error) {
	return withHooks[*Season, SeasonMutation](ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SeasonUpdateOne) SaveX(ctx context.Context) *Season {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SeasonUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SeasonUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SeasonUpdateOne) sqlSave(ctx context.Context) (_node *Season, err error) {
	_spec := sqlgraph.NewUpdateSpec(season.Table, season.Columns, sqlgraph.NewFieldSpec(season.FieldID, field.TypeInt))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Season.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, season.FieldID)
		for _, f := range fields {
			if !season.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != season.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Year(); ok {
		_spec.SetField(season.FieldYear, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedYear(); ok {
		_spec.AddField(season.FieldYear, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Start(); ok {
		_spec.SetField(season.FieldStart, field.TypeTime, value)
	}
	if value, ok := suo.mutation.End(); ok {
		_spec.SetField(season.FieldEnd, field.TypeTime, value)
	}
	if value, ok := suo.mutation.Current(); ok {
		_spec.SetField(season.FieldCurrent, field.TypeBool, value)
	}
	if suo.mutation.LeagueCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.LeagueTable,
			Columns: []string{season.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.LeagueIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   season.LeagueTable,
			Columns: []string{season.LeagueColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(league.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Season{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{season.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
