version: '3.9'

services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mapeleven
      - POSTGRES_USER=mapeleven
      - POSTGRES_DB=mapeleven-dev-db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ./main
    ports:
      - '8080:8080'
    environment:
      - TEST_DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./server:/app/server
    restart: on-failure:10
