services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mapeleven
      - POSTGRES_USER=mapeleven
      - POSTGRES_DB=mapeleven-dev-db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: go run main.go
    ports:
      - '8080:8080'
    environment:
      - TEST_DB_HOST=db
    depends_on:
      - db
    restart: on-failure:10