// Code generated by ent, DO NOT EDIT.

package psdefense

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the psdefense type in the database.
	Label = "ps_defense"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTacklesTotal holds the string denoting the tacklestotal field in the database.
	FieldTacklesTotal = "tackles_total"
	// FieldBlocks holds the string denoting the blocks field in the database.
	FieldBlocks = "blocks"
	// FieldInterceptions holds the string denoting the interceptions field in the database.
	FieldInterceptions = "interceptions"
	// FieldTotalDuels holds the string denoting the totalduels field in the database.
	FieldTotalDuels = "total_duels"
	// FieldWonDuels holds the string denoting the wonduels field in the database.
	FieldWonDuels = "won_duels"
	// EdgePlayerStats holds the string denoting the playerstats edge name in mutations.
	EdgePlayerStats = "playerStats"
	// Table holds the table name of the psdefense in the database.
	Table = "ps_defenses"
	// PlayerStatsTable is the table that holds the playerStats relation/edge. The primary key declared below.
	PlayerStatsTable = "player_stats_psdefense"
	// PlayerStatsInverseTable is the table name for the PlayerStats entity.
	// It exists in this package in order to avoid circular dependency with the "playerstats" package.
	PlayerStatsInverseTable = "player_stats"
)

// Columns holds all SQL columns for psdefense fields.
var Columns = []string{
	FieldID,
	FieldTacklesTotal,
	FieldBlocks,
	FieldInterceptions,
	FieldTotalDuels,
	FieldWonDuels,
}

var (
	// PlayerStatsPrimaryKey and PlayerStatsColumn2 are the table columns denoting the
	// primary key for the playerStats relation (M2M).
	PlayerStatsPrimaryKey = []string{"player_stats_id", "ps_defense_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBlocks holds the default value on creation for the "blocks" field.
	DefaultBlocks int
)

// OrderOption defines the ordering options for the PSDefense queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTacklesTotal orders the results by the tacklesTotal field.
func ByTacklesTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTacklesTotal, opts...).ToFunc()
}

// ByBlocks orders the results by the blocks field.
func ByBlocks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBlocks, opts...).ToFunc()
}

// ByInterceptions orders the results by the interceptions field.
func ByInterceptions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInterceptions, opts...).ToFunc()
}

// ByTotalDuels orders the results by the totalDuels field.
func ByTotalDuels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDuels, opts...).ToFunc()
}

// ByWonDuels orders the results by the wonDuels field.
func ByWonDuels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWonDuels, opts...).ToFunc()
}

// ByPlayerStatsCount orders the results by playerStats count.
func ByPlayerStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlayerStatsStep(), opts...)
	}
}

// ByPlayerStats orders the results by playerStats terms.
func ByPlayerStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayerStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlayerStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayerStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, PlayerStatsTable, PlayerStatsPrimaryKey...),
	)
}
