// Code generated by ent, DO NOT EDIT.

package playerteamseason

import (
	"mapeleven/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldLTE(FieldID, id))
}

// PlayerTeamSeasonID applies equality check predicate on the "player_team_season_id" field. It's identical to PlayerTeamSeasonIDEQ.
func PlayerTeamSeasonID(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldEQ(FieldPlayerTeamSeasonID, v))
}

// PlayerTeamSeasonIDEQ applies the EQ predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDEQ(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldEQ(FieldPlayerTeamSeasonID, v))
}

// PlayerTeamSeasonIDNEQ applies the NEQ predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDNEQ(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldNEQ(FieldPlayerTeamSeasonID, v))
}

// PlayerTeamSeasonIDIn applies the In predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDIn(vs ...int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldIn(FieldPlayerTeamSeasonID, vs...))
}

// PlayerTeamSeasonIDNotIn applies the NotIn predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDNotIn(vs ...int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldNotIn(FieldPlayerTeamSeasonID, vs...))
}

// PlayerTeamSeasonIDGT applies the GT predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDGT(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldGT(FieldPlayerTeamSeasonID, v))
}

// PlayerTeamSeasonIDGTE applies the GTE predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDGTE(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldGTE(FieldPlayerTeamSeasonID, v))
}

// PlayerTeamSeasonIDLT applies the LT predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDLT(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldLT(FieldPlayerTeamSeasonID, v))
}

// PlayerTeamSeasonIDLTE applies the LTE predicate on the "player_team_season_id" field.
func PlayerTeamSeasonIDLTE(v int) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(sql.FieldLTE(FieldPlayerTeamSeasonID, v))
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.Player) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		step := newPlayerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamSeason applies the HasEdge predicate on the "teamSeason" edge.
func HasTeamSeason() predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamSeasonTable, TeamSeasonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamSeasonWith applies the HasEdge predicate on the "teamSeason" edge with a given conditions (other predicates).
func HasTeamSeasonWith(preds ...predicate.TeamSeason) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		step := newTeamSeasonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayerTeamSeason) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayerTeamSeason) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayerTeamSeason) predicate.PlayerTeamSeason {
	return predicate.PlayerTeamSeason(func(s *sql.Selector) {
		p(s.Not())
	})
}
