// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"capstone-cs.eng.utah.edu/mapeleven/mapeleven/pkg/ent/player"
	"capstone-cs.eng.utah.edu/mapeleven/mapeleven/pkg/ent/predicate"
	"capstone-cs.eng.utah.edu/mapeleven/mapeleven/pkg/ent/pspenalty"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PSPenaltyUpdate is the builder for updating PSPenalty entities.
type PSPenaltyUpdate struct {
	config
	hooks    []Hook
	mutation *PSPenaltyMutation
}

// Where appends a list predicates to the PSPenaltyUpdate builder.
func (ppu *PSPenaltyUpdate) Where(ps ...predicate.PSPenalty) *PSPenaltyUpdate {
	ppu.mutation.Where(ps...)
	return ppu
}

// SetFoulsDrawn sets the "foulsDrawn" field.
func (ppu *PSPenaltyUpdate) SetFoulsDrawn(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetFoulsDrawn()
	ppu.mutation.SetFoulsDrawn(i)
	return ppu
}

// AddFoulsDrawn adds i to the "foulsDrawn" field.
func (ppu *PSPenaltyUpdate) AddFoulsDrawn(i int) *PSPenaltyUpdate {
	ppu.mutation.AddFoulsDrawn(i)
	return ppu
}

// SetFoulsCommitted sets the "foulsCommitted" field.
func (ppu *PSPenaltyUpdate) SetFoulsCommitted(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetFoulsCommitted()
	ppu.mutation.SetFoulsCommitted(i)
	return ppu
}

// AddFoulsCommitted adds i to the "foulsCommitted" field.
func (ppu *PSPenaltyUpdate) AddFoulsCommitted(i int) *PSPenaltyUpdate {
	ppu.mutation.AddFoulsCommitted(i)
	return ppu
}

// SetCardsYellow sets the "cardsYellow" field.
func (ppu *PSPenaltyUpdate) SetCardsYellow(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetCardsYellow()
	ppu.mutation.SetCardsYellow(i)
	return ppu
}

// AddCardsYellow adds i to the "cardsYellow" field.
func (ppu *PSPenaltyUpdate) AddCardsYellow(i int) *PSPenaltyUpdate {
	ppu.mutation.AddCardsYellow(i)
	return ppu
}

// SetCardYellowred sets the "cardYellowred" field.
func (ppu *PSPenaltyUpdate) SetCardYellowred(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetCardYellowred()
	ppu.mutation.SetCardYellowred(i)
	return ppu
}

// AddCardYellowred adds i to the "cardYellowred" field.
func (ppu *PSPenaltyUpdate) AddCardYellowred(i int) *PSPenaltyUpdate {
	ppu.mutation.AddCardYellowred(i)
	return ppu
}

// SetCardsRed sets the "cardsRed" field.
func (ppu *PSPenaltyUpdate) SetCardsRed(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetCardsRed()
	ppu.mutation.SetCardsRed(i)
	return ppu
}

// AddCardsRed adds i to the "cardsRed" field.
func (ppu *PSPenaltyUpdate) AddCardsRed(i int) *PSPenaltyUpdate {
	ppu.mutation.AddCardsRed(i)
	return ppu
}

// SetPenaltyWon sets the "penaltyWon" field.
func (ppu *PSPenaltyUpdate) SetPenaltyWon(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetPenaltyWon()
	ppu.mutation.SetPenaltyWon(i)
	return ppu
}

// SetNillablePenaltyWon sets the "penaltyWon" field if the given value is not nil.
func (ppu *PSPenaltyUpdate) SetNillablePenaltyWon(i *int) *PSPenaltyUpdate {
	if i != nil {
		ppu.SetPenaltyWon(*i)
	}
	return ppu
}

// AddPenaltyWon adds i to the "penaltyWon" field.
func (ppu *PSPenaltyUpdate) AddPenaltyWon(i int) *PSPenaltyUpdate {
	ppu.mutation.AddPenaltyWon(i)
	return ppu
}

// SetPenaltyCommited sets the "penaltyCommited" field.
func (ppu *PSPenaltyUpdate) SetPenaltyCommited(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetPenaltyCommited()
	ppu.mutation.SetPenaltyCommited(i)
	return ppu
}

// SetNillablePenaltyCommited sets the "penaltyCommited" field if the given value is not nil.
func (ppu *PSPenaltyUpdate) SetNillablePenaltyCommited(i *int) *PSPenaltyUpdate {
	if i != nil {
		ppu.SetPenaltyCommited(*i)
	}
	return ppu
}

// AddPenaltyCommited adds i to the "penaltyCommited" field.
func (ppu *PSPenaltyUpdate) AddPenaltyCommited(i int) *PSPenaltyUpdate {
	ppu.mutation.AddPenaltyCommited(i)
	return ppu
}

// SetPenaltyScored sets the "penaltyScored" field.
func (ppu *PSPenaltyUpdate) SetPenaltyScored(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetPenaltyScored()
	ppu.mutation.SetPenaltyScored(i)
	return ppu
}

// SetNillablePenaltyScored sets the "penaltyScored" field if the given value is not nil.
func (ppu *PSPenaltyUpdate) SetNillablePenaltyScored(i *int) *PSPenaltyUpdate {
	if i != nil {
		ppu.SetPenaltyScored(*i)
	}
	return ppu
}

// AddPenaltyScored adds i to the "penaltyScored" field.
func (ppu *PSPenaltyUpdate) AddPenaltyScored(i int) *PSPenaltyUpdate {
	ppu.mutation.AddPenaltyScored(i)
	return ppu
}

// SetPenaltyMissed sets the "penaltyMissed" field.
func (ppu *PSPenaltyUpdate) SetPenaltyMissed(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetPenaltyMissed()
	ppu.mutation.SetPenaltyMissed(i)
	return ppu
}

// AddPenaltyMissed adds i to the "penaltyMissed" field.
func (ppu *PSPenaltyUpdate) AddPenaltyMissed(i int) *PSPenaltyUpdate {
	ppu.mutation.AddPenaltyMissed(i)
	return ppu
}

// SetPenaltySaved sets the "penaltySaved" field.
func (ppu *PSPenaltyUpdate) SetPenaltySaved(i int) *PSPenaltyUpdate {
	ppu.mutation.ResetPenaltySaved()
	ppu.mutation.SetPenaltySaved(i)
	return ppu
}

// SetNillablePenaltySaved sets the "penaltySaved" field if the given value is not nil.
func (ppu *PSPenaltyUpdate) SetNillablePenaltySaved(i *int) *PSPenaltyUpdate {
	if i != nil {
		ppu.SetPenaltySaved(*i)
	}
	return ppu
}

// AddPenaltySaved adds i to the "penaltySaved" field.
func (ppu *PSPenaltyUpdate) AddPenaltySaved(i int) *PSPenaltyUpdate {
	ppu.mutation.AddPenaltySaved(i)
	return ppu
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (ppu *PSPenaltyUpdate) SetPlayerID(id int) *PSPenaltyUpdate {
	ppu.mutation.SetPlayerID(id)
	return ppu
}

// SetNillablePlayerID sets the "player" edge to the Player entity by ID if the given value is not nil.
func (ppu *PSPenaltyUpdate) SetNillablePlayerID(id *int) *PSPenaltyUpdate {
	if id != nil {
		ppu = ppu.SetPlayerID(*id)
	}
	return ppu
}

// SetPlayer sets the "player" edge to the Player entity.
func (ppu *PSPenaltyUpdate) SetPlayer(p *Player) *PSPenaltyUpdate {
	return ppu.SetPlayerID(p.ID)
}

// Mutation returns the PSPenaltyMutation object of the builder.
func (ppu *PSPenaltyUpdate) Mutation() *PSPenaltyMutation {
	return ppu.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (ppu *PSPenaltyUpdate) ClearPlayer() *PSPenaltyUpdate {
	ppu.mutation.ClearPlayer()
	return ppu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ppu *PSPenaltyUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ppu.sqlSave, ppu.mutation, ppu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ppu *PSPenaltyUpdate) SaveX(ctx context.Context) int {
	affected, err := ppu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ppu *PSPenaltyUpdate) Exec(ctx context.Context) error {
	_, err := ppu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppu *PSPenaltyUpdate) ExecX(ctx context.Context) {
	if err := ppu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ppu *PSPenaltyUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pspenalty.Table, pspenalty.Columns, sqlgraph.NewFieldSpec(pspenalty.FieldID, field.TypeInt))
	if ps := ppu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ppu.mutation.FoulsDrawn(); ok {
		_spec.SetField(pspenalty.FieldFoulsDrawn, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedFoulsDrawn(); ok {
		_spec.AddField(pspenalty.FieldFoulsDrawn, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.FoulsCommitted(); ok {
		_spec.SetField(pspenalty.FieldFoulsCommitted, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedFoulsCommitted(); ok {
		_spec.AddField(pspenalty.FieldFoulsCommitted, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.CardsYellow(); ok {
		_spec.SetField(pspenalty.FieldCardsYellow, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedCardsYellow(); ok {
		_spec.AddField(pspenalty.FieldCardsYellow, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.CardYellowred(); ok {
		_spec.SetField(pspenalty.FieldCardYellowred, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedCardYellowred(); ok {
		_spec.AddField(pspenalty.FieldCardYellowred, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.CardsRed(); ok {
		_spec.SetField(pspenalty.FieldCardsRed, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedCardsRed(); ok {
		_spec.AddField(pspenalty.FieldCardsRed, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.PenaltyWon(); ok {
		_spec.SetField(pspenalty.FieldPenaltyWon, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedPenaltyWon(); ok {
		_spec.AddField(pspenalty.FieldPenaltyWon, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.PenaltyCommited(); ok {
		_spec.SetField(pspenalty.FieldPenaltyCommited, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedPenaltyCommited(); ok {
		_spec.AddField(pspenalty.FieldPenaltyCommited, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.PenaltyScored(); ok {
		_spec.SetField(pspenalty.FieldPenaltyScored, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedPenaltyScored(); ok {
		_spec.AddField(pspenalty.FieldPenaltyScored, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.PenaltyMissed(); ok {
		_spec.SetField(pspenalty.FieldPenaltyMissed, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedPenaltyMissed(); ok {
		_spec.AddField(pspenalty.FieldPenaltyMissed, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.PenaltySaved(); ok {
		_spec.SetField(pspenalty.FieldPenaltySaved, field.TypeInt, value)
	}
	if value, ok := ppu.mutation.AddedPenaltySaved(); ok {
		_spec.AddField(pspenalty.FieldPenaltySaved, field.TypeInt, value)
	}
	if ppu.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pspenalty.PlayerTable,
			Columns: []string{pspenalty.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppu.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pspenalty.PlayerTable,
			Columns: []string{pspenalty.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ppu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pspenalty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ppu.mutation.done = true
	return n, nil
}

// PSPenaltyUpdateOne is the builder for updating a single PSPenalty entity.
type PSPenaltyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PSPenaltyMutation
}

// SetFoulsDrawn sets the "foulsDrawn" field.
func (ppuo *PSPenaltyUpdateOne) SetFoulsDrawn(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetFoulsDrawn()
	ppuo.mutation.SetFoulsDrawn(i)
	return ppuo
}

// AddFoulsDrawn adds i to the "foulsDrawn" field.
func (ppuo *PSPenaltyUpdateOne) AddFoulsDrawn(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddFoulsDrawn(i)
	return ppuo
}

// SetFoulsCommitted sets the "foulsCommitted" field.
func (ppuo *PSPenaltyUpdateOne) SetFoulsCommitted(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetFoulsCommitted()
	ppuo.mutation.SetFoulsCommitted(i)
	return ppuo
}

// AddFoulsCommitted adds i to the "foulsCommitted" field.
func (ppuo *PSPenaltyUpdateOne) AddFoulsCommitted(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddFoulsCommitted(i)
	return ppuo
}

// SetCardsYellow sets the "cardsYellow" field.
func (ppuo *PSPenaltyUpdateOne) SetCardsYellow(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetCardsYellow()
	ppuo.mutation.SetCardsYellow(i)
	return ppuo
}

// AddCardsYellow adds i to the "cardsYellow" field.
func (ppuo *PSPenaltyUpdateOne) AddCardsYellow(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddCardsYellow(i)
	return ppuo
}

// SetCardYellowred sets the "cardYellowred" field.
func (ppuo *PSPenaltyUpdateOne) SetCardYellowred(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetCardYellowred()
	ppuo.mutation.SetCardYellowred(i)
	return ppuo
}

// AddCardYellowred adds i to the "cardYellowred" field.
func (ppuo *PSPenaltyUpdateOne) AddCardYellowred(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddCardYellowred(i)
	return ppuo
}

// SetCardsRed sets the "cardsRed" field.
func (ppuo *PSPenaltyUpdateOne) SetCardsRed(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetCardsRed()
	ppuo.mutation.SetCardsRed(i)
	return ppuo
}

// AddCardsRed adds i to the "cardsRed" field.
func (ppuo *PSPenaltyUpdateOne) AddCardsRed(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddCardsRed(i)
	return ppuo
}

// SetPenaltyWon sets the "penaltyWon" field.
func (ppuo *PSPenaltyUpdateOne) SetPenaltyWon(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetPenaltyWon()
	ppuo.mutation.SetPenaltyWon(i)
	return ppuo
}

// SetNillablePenaltyWon sets the "penaltyWon" field if the given value is not nil.
func (ppuo *PSPenaltyUpdateOne) SetNillablePenaltyWon(i *int) *PSPenaltyUpdateOne {
	if i != nil {
		ppuo.SetPenaltyWon(*i)
	}
	return ppuo
}

// AddPenaltyWon adds i to the "penaltyWon" field.
func (ppuo *PSPenaltyUpdateOne) AddPenaltyWon(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddPenaltyWon(i)
	return ppuo
}

// SetPenaltyCommited sets the "penaltyCommited" field.
func (ppuo *PSPenaltyUpdateOne) SetPenaltyCommited(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetPenaltyCommited()
	ppuo.mutation.SetPenaltyCommited(i)
	return ppuo
}

// SetNillablePenaltyCommited sets the "penaltyCommited" field if the given value is not nil.
func (ppuo *PSPenaltyUpdateOne) SetNillablePenaltyCommited(i *int) *PSPenaltyUpdateOne {
	if i != nil {
		ppuo.SetPenaltyCommited(*i)
	}
	return ppuo
}

// AddPenaltyCommited adds i to the "penaltyCommited" field.
func (ppuo *PSPenaltyUpdateOne) AddPenaltyCommited(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddPenaltyCommited(i)
	return ppuo
}

// SetPenaltyScored sets the "penaltyScored" field.
func (ppuo *PSPenaltyUpdateOne) SetPenaltyScored(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetPenaltyScored()
	ppuo.mutation.SetPenaltyScored(i)
	return ppuo
}

// SetNillablePenaltyScored sets the "penaltyScored" field if the given value is not nil.
func (ppuo *PSPenaltyUpdateOne) SetNillablePenaltyScored(i *int) *PSPenaltyUpdateOne {
	if i != nil {
		ppuo.SetPenaltyScored(*i)
	}
	return ppuo
}

// AddPenaltyScored adds i to the "penaltyScored" field.
func (ppuo *PSPenaltyUpdateOne) AddPenaltyScored(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddPenaltyScored(i)
	return ppuo
}

// SetPenaltyMissed sets the "penaltyMissed" field.
func (ppuo *PSPenaltyUpdateOne) SetPenaltyMissed(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetPenaltyMissed()
	ppuo.mutation.SetPenaltyMissed(i)
	return ppuo
}

// AddPenaltyMissed adds i to the "penaltyMissed" field.
func (ppuo *PSPenaltyUpdateOne) AddPenaltyMissed(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddPenaltyMissed(i)
	return ppuo
}

// SetPenaltySaved sets the "penaltySaved" field.
func (ppuo *PSPenaltyUpdateOne) SetPenaltySaved(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.ResetPenaltySaved()
	ppuo.mutation.SetPenaltySaved(i)
	return ppuo
}

// SetNillablePenaltySaved sets the "penaltySaved" field if the given value is not nil.
func (ppuo *PSPenaltyUpdateOne) SetNillablePenaltySaved(i *int) *PSPenaltyUpdateOne {
	if i != nil {
		ppuo.SetPenaltySaved(*i)
	}
	return ppuo
}

// AddPenaltySaved adds i to the "penaltySaved" field.
func (ppuo *PSPenaltyUpdateOne) AddPenaltySaved(i int) *PSPenaltyUpdateOne {
	ppuo.mutation.AddPenaltySaved(i)
	return ppuo
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (ppuo *PSPenaltyUpdateOne) SetPlayerID(id int) *PSPenaltyUpdateOne {
	ppuo.mutation.SetPlayerID(id)
	return ppuo
}

// SetNillablePlayerID sets the "player" edge to the Player entity by ID if the given value is not nil.
func (ppuo *PSPenaltyUpdateOne) SetNillablePlayerID(id *int) *PSPenaltyUpdateOne {
	if id != nil {
		ppuo = ppuo.SetPlayerID(*id)
	}
	return ppuo
}

// SetPlayer sets the "player" edge to the Player entity.
func (ppuo *PSPenaltyUpdateOne) SetPlayer(p *Player) *PSPenaltyUpdateOne {
	return ppuo.SetPlayerID(p.ID)
}

// Mutation returns the PSPenaltyMutation object of the builder.
func (ppuo *PSPenaltyUpdateOne) Mutation() *PSPenaltyMutation {
	return ppuo.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (ppuo *PSPenaltyUpdateOne) ClearPlayer() *PSPenaltyUpdateOne {
	ppuo.mutation.ClearPlayer()
	return ppuo
}

// Where appends a list predicates to the PSPenaltyUpdate builder.
func (ppuo *PSPenaltyUpdateOne) Where(ps ...predicate.PSPenalty) *PSPenaltyUpdateOne {
	ppuo.mutation.Where(ps...)
	return ppuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ppuo *PSPenaltyUpdateOne) Select(field string, fields ...string) *PSPenaltyUpdateOne {
	ppuo.fields = append([]string{field}, fields...)
	return ppuo
}

// Save executes the query and returns the updated PSPenalty entity.
func (ppuo *PSPenaltyUpdateOne) Save(ctx context.Context) (*PSPenalty, error) {
	return withHooks(ctx, ppuo.sqlSave, ppuo.mutation, ppuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ppuo *PSPenaltyUpdateOne) SaveX(ctx context.Context) *PSPenalty {
	node, err := ppuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ppuo *PSPenaltyUpdateOne) Exec(ctx context.Context) error {
	_, err := ppuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ppuo *PSPenaltyUpdateOne) ExecX(ctx context.Context) {
	if err := ppuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ppuo *PSPenaltyUpdateOne) sqlSave(ctx context.Context) (_node *PSPenalty, err error) {
	_spec := sqlgraph.NewUpdateSpec(pspenalty.Table, pspenalty.Columns, sqlgraph.NewFieldSpec(pspenalty.FieldID, field.TypeInt))
	id, ok := ppuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PSPenalty.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ppuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pspenalty.FieldID)
		for _, f := range fields {
			if !pspenalty.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pspenalty.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ppuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ppuo.mutation.FoulsDrawn(); ok {
		_spec.SetField(pspenalty.FieldFoulsDrawn, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedFoulsDrawn(); ok {
		_spec.AddField(pspenalty.FieldFoulsDrawn, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.FoulsCommitted(); ok {
		_spec.SetField(pspenalty.FieldFoulsCommitted, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedFoulsCommitted(); ok {
		_spec.AddField(pspenalty.FieldFoulsCommitted, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.CardsYellow(); ok {
		_spec.SetField(pspenalty.FieldCardsYellow, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedCardsYellow(); ok {
		_spec.AddField(pspenalty.FieldCardsYellow, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.CardYellowred(); ok {
		_spec.SetField(pspenalty.FieldCardYellowred, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedCardYellowred(); ok {
		_spec.AddField(pspenalty.FieldCardYellowred, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.CardsRed(); ok {
		_spec.SetField(pspenalty.FieldCardsRed, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedCardsRed(); ok {
		_spec.AddField(pspenalty.FieldCardsRed, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.PenaltyWon(); ok {
		_spec.SetField(pspenalty.FieldPenaltyWon, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedPenaltyWon(); ok {
		_spec.AddField(pspenalty.FieldPenaltyWon, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.PenaltyCommited(); ok {
		_spec.SetField(pspenalty.FieldPenaltyCommited, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedPenaltyCommited(); ok {
		_spec.AddField(pspenalty.FieldPenaltyCommited, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.PenaltyScored(); ok {
		_spec.SetField(pspenalty.FieldPenaltyScored, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedPenaltyScored(); ok {
		_spec.AddField(pspenalty.FieldPenaltyScored, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.PenaltyMissed(); ok {
		_spec.SetField(pspenalty.FieldPenaltyMissed, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedPenaltyMissed(); ok {
		_spec.AddField(pspenalty.FieldPenaltyMissed, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.PenaltySaved(); ok {
		_spec.SetField(pspenalty.FieldPenaltySaved, field.TypeInt, value)
	}
	if value, ok := ppuo.mutation.AddedPenaltySaved(); ok {
		_spec.AddField(pspenalty.FieldPenaltySaved, field.TypeInt, value)
	}
	if ppuo.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pspenalty.PlayerTable,
			Columns: []string{pspenalty.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ppuo.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pspenalty.PlayerTable,
			Columns: []string{pspenalty.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PSPenalty{config: ppuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ppuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pspenalty.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ppuo.mutation.done = true
	return _node, nil
}
